const elements = {
  blogList: document.getElementById("blogs"),
  blogTitle: document.getElementById("title"),
  blogContent: document.getElementById("content"),
  blogAuthor: document.getElementById("author"),
  blogDate: document.getElementById("date"),
  blogImgUrl: document.getElementById("blogImgUrl"),
  blogCategory: document.getElementById("category"),
  blogForm: document.getElementById("blog-form"),
  newBlogTitle: document.getElementById("new-title"),
  newBlogContent: document.getElementById("new-content"),
  newBlogAuthor: document.getElementById("new-author"),
  newBlogDate: document.getElementById("new-date"),
  newBlogImgUrl: document.getElementById("new-blogImgUrl"),
  newBlogCategory: document.getElementById("new-category"),
  updateBlogForm: document.getElementById("update-blog-form"),
  editModal: document.getElementById("exampleModal"),
  newModal: document.getElementById("staticBackdrop"),
  categoryFilter: document.getElementById("category-filter"),
  searchFilter: document.getElementById("search-filter"),
  authorFilter: document.getElementById("author-filter"),
  resetButton: document.getElementById("reset-btn"),
  sort: document.getElementById("sort"),
  welcomeBlog: document.getElementById("welcome-blog"),
  topRatedBlogs: document.getElementById("top-rated-blogs"),
  contentBlogModal: document.getElementById("content-blog-modal"),
};

export { elements };