const elements = {
  productList: document.getElementById("products"),
  productName: document.getElementById("name"),
  productContent: document.getElementById("content"),
  productPrice: document.getElementById("price"),
  productImgUrl: document.getElementById("imgUrl"),
  productCategory: document.getElementById("category"),
  productForm: document.getElementById("product-form"),
  productStock: document.getElementById("stock"),
  newProductName: document.getElementById("new-name"),
  newProductContent: document.getElementById("new-content"),
  newProductPrice: document.getElementById("new-price"),
  newProductImgUrl: document.getElementById("new-imgUrl"),
  newProductCategory: document.getElementById("new-category"),
  newProductStock: document.getElementById("new-stock"),
  editModal: document.getElementById("exampleModal"),
  newModal: document.getElementById("staticBackdrop"),
  categoryFilter: document.getElementById("category-filter"),
  searchFilter: document.getElementById("search-filter"),
  detailModal: document.getElementById("detail-modal"),
  cartBadge: document.getElementById("cart-quantity"),
  cartModal: document.getElementById("cartModal"),
  cartButton: document.getElementById("cart-button"),
  cartList: document.getElementById("cart-list"),
  productDetail: document.getElementById("product-detail"),
  categoryAll: document.getElementById("category-all"),
  categoryCake: document.getElementById("category-cake"),
  categoryCupcake: document.getElementById("category-cupcake"),
  categoryCookie: document.getElementById("category-cookie"),
  sortPriceAsc: document.getElementById("sort-price-asc"),
  sortPriceDesc: document.getElementById("sort-price-desc"),
  sortNameAsc: document.getElementById("sort-name-asc"),
  sortNameDesc: document.getElementById("sort-name-desc"),
  order : document.getElementById("order"),
};

export { elements };
