import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>main layout</h1>
        <ul>
          <li>
            <Link href="/about">abouuut</Link>
            <Link
              href={{
                pathname: "/blog",
                query: {
                  id: "1",
                  name: "test",
                },
              }}
            >
              blogg
            </Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
